// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5EZ4Qd6MeXeu3OzMbgSMqg9iNDK5gCVs',
    appId: '1:911869093508:web:0e87f0de68d9fd76cd84d1',
    messagingSenderId: '911869093508',
    projectId: 'techdrive-1495f',
    authDomain: 'techdrive-1495f.firebaseapp.com',
    storageBucket: 'techdrive-1495f.firebasestorage.app',
    measurementId: 'G-6QMRZ9JDXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn2t29TEUo9zERmuL5zL033Cz7gAibwf0',
    appId: '1:911869093508:android:e9031bcdd0006a41cd84d1',
    messagingSenderId: '911869093508',
    projectId: 'techdrive-1495f',
    storageBucket: 'techdrive-1495f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBZzMH65D2IaOwAdc2V2LBA4ynWfgUAlc',
    appId: '1:911869093508:ios:bce99ded6b62a532cd84d1',
    messagingSenderId: '911869093508',
    projectId: 'techdrive-1495f',
    storageBucket: 'techdrive-1495f.firebasestorage.app',
    androidClientId: '911869093508-evrt4girgful6pbmclubuflk2m7ternd.apps.googleusercontent.com',
    iosClientId: '911869093508-9727jm2m12btuo2uio3659m07ft4sgk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.techDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBZzMH65D2IaOwAdc2V2LBA4ynWfgUAlc',
    appId: '1:911869093508:ios:bce99ded6b62a532cd84d1',
    messagingSenderId: '911869093508',
    projectId: 'techdrive-1495f',
    storageBucket: 'techdrive-1495f.firebasestorage.app',
    androidClientId: '911869093508-evrt4girgful6pbmclubuflk2m7ternd.apps.googleusercontent.com',
    iosClientId: '911869093508-9727jm2m12btuo2uio3659m07ft4sgk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.techDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5EZ4Qd6MeXeu3OzMbgSMqg9iNDK5gCVs',
    appId: '1:911869093508:web:a285fbb2094d3592cd84d1',
    messagingSenderId: '911869093508',
    projectId: 'techdrive-1495f',
    authDomain: 'techdrive-1495f.firebaseapp.com',
    storageBucket: 'techdrive-1495f.firebasestorage.app',
    measurementId: 'G-YZJ6QYT9RF',
  );
}
